export enum CampaignScheduleIntervalEnum {
  FIVE_MINUTES = 'FIVE_MINUTES',
  TEN_MINUTES = 'TEN_MINUTES',
  THIRTY_MINUTES = 'THIRTY_MINUTES',
  ONE_HOUR = 'ONE_HOUR',
  THREE_HOURS = 'THREE_HOURS',
  SIX_HOURS = 'SIX_HOURS',
  ONE_DAY = 'ONE_DAY',
  ONE_WEEK = 'ONE_WEEK'
}
